
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_search_development

test: &test
  <<: *default
  database: movie_search_test

production:
  <<: *default
  database: movie_search_production
  username: movie_search
  password: <%= ENV['MOVIE_SEARCH_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
